# Generated by Django 4.0.6 on 2022-07-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('nombre', models.TextField()),
                ('apepat', models.TextField()),
                ('apemat', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
